apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: "HomeLab"
    theme: dark
  bookmarks.yaml: |
    - Dev:
        - Kubernetes Docs:
            - href: https://kubernetes.io/docs/home/
              description: Kubernetes documentation
        - FluxCD Docs:
            - href: https://fluxcd.io/docs/
              description: Flux CD documentation
  services.yaml: |
    - Homelab:
        - Homepage:
            icon: homepage
            href: http://homepage.homelab
            description: Your homelab landing page
        - HomeLab Wiki:
            icon: bookstack.png
            href: http://192.168.2.175:4292/
            description: Documentations about my homelab.
  widgets.yaml: |
    - kubernetes:
        cluster: { show: true, cpu: true, memory: true, showLabel: true, label: "cluster" }
        nodes: { show: true, cpu: true, memory: true, showLabel: true }
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
  custom.css: ""
  custom.js: ""
  docker.yaml: ""
