apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage
resources:
  - ns.yaml
  - deploy.yaml
  - service.yaml
  - ingress.yaml
  - secret.yaml
  - serviceaccount.yaml
  - rbac.yaml
  - config.yaml
